# fly.toml app configuration file generated for hilarious-heliosphere on 2023-12-01T00:48:43-05:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "${APP_NAME}"
primary_region = "${APP_REGION}"

# See `.env.example` for the required secret variables. Technically, you can
# set all the required variables as secrets
[env]
# If you set the port using the environment variable, make sure to not set it
# explicitly in `uwsgi.ini` otherwise the deployment will fail
LD_SERVER_PORT = "9999"
DB_PATH = "/etc/linkding/data/db.sqlite3"
LITESTREAM_REPLICA_PATH = "linkding_replica.sqlite3"

[http_service]
internal_port = 9999
force_https = true
auto_stop_machines = true
auto_start_machines = true
min_machines_running = 0
processes = ["app"]

[mounts]
source = "linkding_data"
destination = "/etc/linkding/data"

[[vm]]
cpu_kind = "shared"
cpus = 1
memory_mb = 512
